# Based on https://github.com/jekyll/minima/blob/master/_config.yml
author: Nikita Karetnikov
email: nikita@karetnikov.org
# social links
twitter_username: karetnikovn
github_username:  nkaretnikov

theme: minima

show_excerpts: false  # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
